# Uncomment the next line to define a global platform for your project
 platform :ios, '12.2'

target 'NOSWasteManager' do
  pod 'DeckTransition', '~> 2.0'
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NOSWasteManager

  target 'NOSWasteManagerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NOSWasteManagerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
